Repository vertelab/odoo-outplacement, pull requests merged in 2020-12, with the labels that each got.

#3 [ADD] outplacement_order_interpretor AFC-1154: added module outplacem…
  outplacement_order_interpretor/__init__.py
  outplacement_order_interpretor/__manifest__.py
  outplacement_order_interpretor/data/mail_data.xml
  outplacement_order_interpretor/models/__init__.py
  outplacement_order_interpretor/models/mail_activity.py
  outplacement_order_interpretor/models/res_partner.py
  outplacement_order_interpretor/static/description/icon.png
  outplacement_order_interpretor/static/description/screen1.png
  outplacement_order_interpretor/views/mail_activity_views.xml
  outplacement_order_interpretor/views/res_partner_view.xml
Labels: Prio 2

#6 [ADD] AFC-1486a Send Joint Planning: Add outplacement_joint_planning
  outplacement_joint_planning/__init__.py
  outplacement_joint_planning/__manifest__.py
  outplacement_joint_planning/models/__init__.py
  outplacement_joint_planning/models/outplacement.py
  outplacement_joint_planning/views/outplacement_view.xml
Labels: Prio 1, question

#7 [ADD] outplacement_completion_report_ipf_client AFC-1486c: Send GP accs DAFA to BÄR
  outplacement_completion_report_ipf_client/__manifest__.py
  outplacement_completion_report_ipf_client/models/client_config.py
  outplacement_completion_report_ipf_client/views/client_config_views.xml
Labels: Prio 2, need install / smoke test

#13 Dev 12.0 dafa sprint 2 afc 1555 sale outplacement fields
  sale_outplacement/models/outplacement.py
  sale_outplacement/models/product_product.py
  sale_outplacement/views/product_product_views.xml
Labels: Do not merge yet, need install / smoke test

#8 [ADD] outplacement_deviation_report AFC-1174: Add modules
  outplacement_deviation_report/__init__.py
  outplacement_deviation_report/__manifest__.py
  outplacement_deviation_report/views/project_views.xml
  outplacement_deviation_report/wizards/__init__.py
  outplacement_deviation_report/wizards/deviation_report_wizard.py
  outplacement_deviation_report/wizards/deviation_report_wizard.xml
Labels: Prio 2, dependency missing, need install / smoke test

#18 AFC-1566 outplacement_partner_education: added education views that reflect rela…
  outplacement_partner_education/__init__.py
  outplacement_partner_education/__manifest__.py
  outplacement_partner_education/models/__init__.py
  outplacement_partner_education/models/outplacement.py
  outplacement_partner_education/views/outplacement_view.xml
Labels: Do not merge yet

#19 outplacement_partner_jobs AFC-1567: adds tab to outplacement form vie…
  outplacement_partner_jobs/__init__.py
  outplacement_partner_jobs/__manifest__.py
  outplacement_partner_jobs/models/__init__.py
  outplacement_partner_jobs/models/outplacement.py
  outplacement_partner_jobs/views/outplacement_view.xml
Labels: need install / smoke test

#20 AFC-1562: outplacement added related fields for partner address
  outplacement/models/outplacement.py
  outplacement/views/outplacement_view.xml
  outplacement_partner_jobs/views/outplacement_view.xml
  outplacement_partner_ssn/__init__.py
  outplacement_partner_ssn/__manifest__.py
  outplacement_partner_ssn/models/__init__.py
  outplacement_partner_ssn/models/outplacement.py
  outplacement_partner_ssn/views/outplacement_view.xml
Labels: Prio 1

#23 Afc 1586 outplacment_order_interpreter changed language to tolkportalens ids
  outplacement_order_interpretor/__manifest__.py
  outplacement_order_interpretor/models/mail_activity.py
Labels: Prio 2

#27 [MOV] outplacement_deviationreport_ipf_*: Copied from odoo-hr
  outplacement_deviationreport_ipf_client/__init__.py
  outplacement_deviationreport_ipf_client/__manifest__.py
  outplacement_deviationreport_ipf_client/models/__init__.py
  outplacement_deviationreport_ipf_client/models/client_config.py
  outplacement_deviationreport_ipf_client/models/request_history.py
  outplacement_deviationreport_ipf_client/security/ir.model.access.csv
  outplacement_deviationreport_ipf_client/static/description/icon.png
  outplacement_deviationreport_ipf_client/views/client_config_views.xml
  outplacement_deviationreport_ipf_server/__init__.py
  outplacement_deviationreport_ipf_server/__manifest__.py
  outplacement_deviationreport_ipf_server/controllers/__init__.py
  outplacement_deviationreport_ipf_server/controllers/main.py
  outplacement_deviationreport_ipf_server/controllers/token.py
  outplacement_deviationreport_ipf_server/models/__init__.py
  outplacement_deviationreport_ipf_server/models/ir_http.py
  outplacement_deviationreport_ipf_server/static/description/icon.png
Labels: Prio 1
